# Generated by Django 6.1 on 2026-08-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='edited_fields',
            field=models.JSONField(blank=True, default=list, help_text="List of field names that were edited after creation (e.g. ['title', 'details', 'images'])"),
        ),
    ]
