# Generated by Django 6.1 on 2026-08-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_edited_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('cancelled', 'Cancelled'), ('ended', 'Ended'), ('funded', 'Fully Funded')], default='running', max_length=10),
        ),
    ]
