# Generated by Django 6.1 on 2026-08-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_funded_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('cancelled', 'Cancelled'), ('ended', 'Ended'), ('funded', 'Fully Funded'), ('coming_soon', 'Coming Soon')], default='running', max_length=15),
        ),
    ]
