# Generated by Django 6.1 on 2026-08-17 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text="The user's input, truncated to 500 characters.", max_length=500, verbose_name='user message')),
                ('response_snippet', models.CharField(blank=True, help_text='First 200 characters of the AI response.', max_length=200, verbose_name='response snippet')),
                ('intent', models.CharField(blank=True, default='general', help_text="The intent category detected from the user's message.", max_length=30, verbose_name='classified intent')),
                ('was_refused', models.BooleanField(default=False, help_text='Whether this message was flagged as off-topic or prompt injection.', verbose_name='was refused')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Log',
                'verbose_name_plural': 'Chat Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
