# Generated by Django 6.1 on 2026-08-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='error_details',
            field=models.TextField(blank=True, default='', help_text='Full stack trace or error message when an error occurs.', verbose_name='error details'),
        ),
    ]
