# Generated by Django 6.0.8 on 2026-08-05 18:45

import accounts.models
import accounts.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('mobile_phone', models.CharField(help_text='Egyptian mobile number, e.g. 01012345678', max_length=20, validators=[accounts.validators.validate_egyptian_phone], verbose_name='mobile phone')),
                ('profile_picture', models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to=accounts.models.profile_picture_path, verbose_name='profile picture')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='birthdate')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook profile URL')),
                ('country', models.CharField(blank=True, choices=[('EG', 'Egypt'), ('SA', 'Saudi Arabia'), ('AE', 'United Arab Emirates'), ('OT', 'Other')], max_length=2, null=True, verbose_name='country')),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether this account has been activated via email.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
    ]
